### ISSUE TITLE
The client is not disconnect when ser2tcp is killed

### ISSUE THREAD

**Issue by it-praktyk** [cortexm/ser2tcp#2] opened 2017-04-26 13:14 UTC
The configuration the same like in #1 

I stopped ser2tcp from the console of Raspberry Pi (using 'ctrl+c'), a telnet client was still connected.

When I tried rerun ser2tcp I received

```
root@piconsoleserver3:/home/pi/ser2tcp-python# python3 ser2tcp.py /dev/ttyUSB0 115200 NONE ONE -l 0:10001 -v -t
2017-04-26 12:48:41,899 Starting server (listen: 0:10001, serial: /dev/ttyUSB0:115200)..
Traceback (most recent call last):
  File "ser2tcp.py", line 287, in <module>
    main()
  File "ser2tcp.py", line 271, in main
    log=log,
  File "ser2tcp.py", line 123, in __init__
    self._socket.bind((address, port))
OSError: [Errno 98] Address already in use
2017-04-26 12:48:42,030 Exiting..
Exception ignored in: <bound method Ser2TcpServer.__del__ of <__main__.Ser2TcpServer object at 0xb68ab450>>
Traceback (most recent call last):
  File "ser2tcp.py", line 141, in __del__
    self.close()
  File "ser2tcp.py", line 188, in close
    self._clients_disconnect()
  File "ser2tcp.py", line 181, in _clients_disconnect
    for con in self._connections:
AttributeError: 'Ser2TcpServer' object has no attribute '_connections'
root@piconsoleserver3:/home/pi/ser2tcp-python# 
```

After disconnecting a telnet client (using 'ctrl + ]'  what was my escape character) when I try start server I see

```
root@piconsoleserver3:/home/pi/ser2tcp-python# python3 ser2tcp.py /dev/ttyUSB0 115200 NONE ONE -l 0:10001 -v -t
2017-04-26 12:59:46,591 Starting server (listen: 0:10001, serial: /dev/ttyUSB0:115200)..
Traceback (most recent call last):
  File "ser2tcp.py", line 287, in <module>
    main()
  File "ser2tcp.py", line 271, in main
    log=log,
  File "ser2tcp.py", line 123, in __init__
    self._socket.bind((address, port))
OSError: [Errno 98] Address already in use
2017-04-26 12:59:46,724 Exiting..
Exception ignored in: <bound method Ser2TcpServer.__del__ of <__main__.Ser2TcpServer object at 0xb6971450>>
Traceback (most recent call last):
  File "ser2tcp.py", line 141, in __del__
    self.close()
  File "ser2tcp.py", line 188, in close
    self._clients_disconnect()
  File "ser2tcp.py", line 181, in _clients_disconnect
    for con in self._connections:
AttributeError: 'Ser2TcpServer' object has no attribute '_connections'
```

Netstat outpout

```
root@piconsoleserver3:/home/pi/ser2tcp-python# netstat -nap | grep 10001
tcp        0      0 0.0.0.0:10001           0.0.0.0:*               LISTEN      2653/python3    
tcp        7      0 10.1.3.22:10001       10.1.3.147:50266      CLOSE_WAIT  2653/python3    
```

I can run ser2tcp only when I kill remaining python3 process
```
kill -9 2653
```

**Comment by it-praktyk** [comment] 2017-04-26 13:17
Generally I very like your product!

**Comment by pavelrevak** [comment] 2017-04-27 06:27
probably it is caused by the old version of pyserial
try first to use pyserial installed from pip, after this it should work, I tested this on Debian and MAC OS and without problems
```
$ sudo pip3 install pyserial
Downloading/unpacking pyserial
  Downloading pyserial-3.3-py2.py3-none-any.whl (189kB): 189kB downloaded
Installing collected packages: pyserial
Successfully installed pyserial
Cleaning up...
$ python3 ser2tcp.py /dev/ttyAMA0 115200 EVEN -l 0:10001 -t -v
2017-04-27 08:18:24,772 Starting server (listen: 0:10001, serial: /dev/ttyAMA0:115200)..
2017-04-27 08:18:27,070 Serial /dev/ttyAMA0 connected
2017-04-27 08:18:27,072 Client connected: 127.0.0.1:37102
```
here killed by ctrl+c or with kill (same effect)
```
^C2017-04-27 08:18:31,998 Exiting..
2017-04-27 08:18:31,999 Client disconnected: 127.0.0.1:37102
2017-04-27 08:18:32,001 Serial /dev/ttyAMA0 disconnected
2017-04-27 08:18:32,002 Exiting..
```
on client while server is killed:
```
$ telnet 0 10001
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by pavelrevak** [comment] 2017-04-27 06:36
I closing this because it is probably caused old version of pyserial

**Closed as completed by pavelrevak** 2017-04-27 06:36 UTC
